// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: product/items.proto

package product_svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive bool          `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Detail   []*ItemDetail `protobuf:"bytes,4,rep,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ItemsResponse) Reset() {
	*x = ItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_items_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsResponse) ProtoMessage() {}

func (x *ItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_items_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsResponse.ProtoReflect.Descriptor instead.
func (*ItemsResponse) Descriptor() ([]byte, []int) {
	return file_product_items_proto_rawDescGZIP(), []int{0}
}

func (x *ItemsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemsResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ItemsResponse) GetDetail() []*ItemDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ItemDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId   int64   `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ShopId   int64   `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName string  `protobuf:"bytes,4,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Qty      int64   `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_items_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_product_items_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_product_items_proto_rawDescGZIP(), []int{1}
}

func (x *ItemDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemDetail) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemDetail) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ItemDetail) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ItemDetail) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemDetail) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type ItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive bool  `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
}

func (x *ItemsRequest) Reset() {
	*x = ItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_items_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsRequest) ProtoMessage() {}

func (x *ItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_items_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsRequest.ProtoReflect.Descriptor instead.
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return file_product_items_proto_rawDescGZIP(), []int{2}
}

func (x *ItemsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemsRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_product_items_proto protoreflect.FileDescriptor

var file_product_items_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x76,
	0x63, 0x22, 0x7f, 0x0a, 0x0d, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x76, 0x63, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x71, 0x74, 0x79, 0x22, 0x3a, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x32, 0x57, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x76, 0x63, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x64, 0x69,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x73, 0x76, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_product_items_proto_rawDescOnce sync.Once
	file_product_items_proto_rawDescData = file_product_items_proto_rawDesc
)

func file_product_items_proto_rawDescGZIP() []byte {
	file_product_items_proto_rawDescOnce.Do(func() {
		file_product_items_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_items_proto_rawDescData)
	})
	return file_product_items_proto_rawDescData
}

var file_product_items_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_product_items_proto_goTypes = []any{
	(*ItemsResponse)(nil), // 0: productsvc.ItemsResponse
	(*ItemDetail)(nil),    // 1: productsvc.ItemDetail
	(*ItemsRequest)(nil),  // 2: productsvc.ItemsRequest
}
var file_product_items_proto_depIdxs = []int32{
	1, // 0: productsvc.ItemsResponse.detail:type_name -> productsvc.ItemDetail
	2, // 1: productsvc.ProductService.GetProductByID:input_type -> productsvc.ItemsRequest
	0, // 2: productsvc.ProductService.GetProductByID:output_type -> productsvc.ItemsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_items_proto_init() }
func file_product_items_proto_init() {
	if File_product_items_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_items_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_items_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ItemDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_items_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_items_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_items_proto_goTypes,
		DependencyIndexes: file_product_items_proto_depIdxs,
		MessageInfos:      file_product_items_proto_msgTypes,
	}.Build()
	File_product_items_proto = out.File
	file_product_items_proto_rawDesc = nil
	file_product_items_proto_goTypes = nil
	file_product_items_proto_depIdxs = nil
}
